const actions = {
    CHANGE_CLASS_NAME: 'CHANGE_CLASS_NAME',
    CHANGE_LOGIN: 'CHANGE_LOGIN',
    REMOVE_LOGIN: 'REMOVE_LOGIN',
    CLEAR_LOGIN_ERROR: 'CLEAR_LOGIN_ERROR',
    LOGIN_USER: 'LOGIN_USER',
    SIGN_USER: 'SIGN_USER',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    CLEAR_SIGNIN_ERROR: 'CLEAR_SIGNIN_ERROR',
    UPDATE_PROFILE_PICTURE: 'UPDATE_PROFILE_PICTURE',
    INVALID_TOKEN: 'INVALID_TOKEN',
    CALL_MODAL: 'CALL_MODAL',
    LOADING: 'LOADING'
}
export default actions;
